### ISSUE TITLE
Crushed Cobalt Recipe is no longe working in 1.16-b1.4.0b

### ISSUE THREAD

**Issue by ffuentesm** [JerryLu086/More-Create-Stuffs#7]
all of the MoreCreateStuffs - 1.16-b1.4.0a and MoreCreateStuffs - 1.16-b1.4.0b download files are just MoreCreateStuffs - 1.16-b1.4.0 file. 

![image](https://user-images.githubusercontent.com/44974827/124681041-ae423500-de95-11eb-8f0c-3f3f7c5e36d3.png)

**Comment by JerryLu086** [comment]
Might fix it, thanks for reporting. Sorry I'm a bit busier than usual, don't know will this get fixed quickly or not.
