### ISSUE TITLE
Tooltip error, see log

### ISSUE THREAD

**Issue by DireWaff** [JerryLu086/More-Create-Stuffs#9]
![image](https://user-images.githubusercontent.com/88416421/128117902-88df9c6a-1d5d-4ff0-af55-2770226aec03.png)
[crash-2021-08-03_23.12.55-client.txt](https://github.com/JerryLu086/More-Create-Stuffs/files/6928400/crash-2021-08-03_23.12.55-client.txt)
After trying to craft a diving helmet, getting this crash to main menu. Kind of at a loss as what to do. Lavender Tea isn't an item in my pack as far as I can tell.

Let me know what I can do to help!

**Comment by DireWaff** [comment]
Some additional notes: The crash reports vary some, some mentioning "crushed tungsten" and so on. I apologize, but I've lost a few of the logs since I've been doing some troubleshooting of my own. 
I have these files as well:
[latest.log](https://github.com/JerryLu086/More-Create-Stuffs/files/6933186/latest.log)

**Comment by JerryLu086** [comment]
Sorry but was this issue solved on CF iirc? o.O
Didn't really check this repository for a while.
